@echo off
echo Installing Global Dependencies...

echo Installing Expo CLI...
call npm install --global expo-cli

echo Installing Yarn...
call npm install --global yarn

echo Installing react-native...
call npm install --global react-native

echo Installing create-react-native-app...
call npm install --global create-react-native-app

echo Dependencies Installed Successfully!